#!/usr/bin/env bash
# Installs and setup haproxy
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
sudo echo "
   frontend www
        bind *:80
        default_backend nginx_pool

   backend nginx_pool
        balance roundrobin
        mode http
        server 373394-web-01 35.174.209.78:80 check
        server 373394-web-02 54.167.174.202:80 check
" >> /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart

